on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04

    env:
      MIX_ENV: test
      SUPABASE_TEST_URL: ${{ secrets.SUPABASE_TEST_URL }}
      SUPABASE_TEST_KEY: ${{ secrets.SUPABASE_TEST_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1.7
        with:
          otp-version: "23.3"
          elixir-version: "1.11.3"
      - run: mix deps.get
      - run: mix coveralls.github
